### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [tugcekeser/SimpleTwitter#1]
Hello Rabia,
Looks like you added git from previous homework2.

Please update your `README.md` to include a GIF or video walkthrough [as described here](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-creating-the-project-readme) and then [re-submit your project](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-submitting-through-course-system) through the course system.

**Comment by tugcekeser** [comment]
I will update the demo. I guess wrong demo plays now.

**Comment by tugcekeser** [comment]
Updated. please review again.

**Comment by codepathreview** [comment]
:+1: Great work. A few notes after checking out the code:

* Good work on a clean UI, looks polished
* Good job moving compose to `FloatingActionButton`
* Good to see you were able to format the timestamp cleanly 
* Nice touch with the character count being displayed while the user composes a tweet
* Nice work using `SwipeRefreshLayout` library for easy timeline refreshes
* Glad to see you made the compose activity into a dialog instead
* Good to see you added the new tweet directly to the home timeline after it was successfully posted to Twitter.
* Consider adding local persistence of tweets by using `DBFlow` (not file) in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/DBFlow-Guide) for more details.
* Good work using [Parceler](https://guides.codepath.com/android/Using-Parceler) instead of directly using Parcelable to reduce boilerplate and conveniently read/write objects to parcel.
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
